/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universidad;

import javax.swing.JOptionPane;
/**
 *
 * @author juan
 */
public class MenuOption extends javax.swing.JFrame {
    
    public static Arreglos arreglo = new Arreglos();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuOption.class.getName());

    /**
     * Creates new form MenuOption
     */
    public MenuOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BusesRegister = new javax.swing.JButton();
        RegisterDayWeekWork = new javax.swing.JButton();
        AnalysisWeek = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BusesRegister.setText("Buses Register ");
        BusesRegister.addActionListener(this::BusesRegisterActionPerformed);

        RegisterDayWeekWork.setText("Record of day worked and  bus used  ");
        RegisterDayWeekWork.setEnabled(false);
        RegisterDayWeekWork.addActionListener(this::RegisterDayWeekWorkActionPerformed);

        AnalysisWeek.setText("Analysis of the Week");
        AnalysisWeek.setEnabled(false);
        AnalysisWeek.addActionListener(this::AnalysisWeekActionPerformed);

        jLabel1.setText("Menu of Options ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BusesRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterDayWeekWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AnalysisWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(BusesRegister)
                .addGap(18, 18, 18)
                .addComponent(RegisterDayWeekWork)
                .addGap(18, 18, 18)
                .addComponent(AnalysisWeek)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterDayWeekWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDayWeekWorkActionPerformed
        RegisterDayWeekWork window = new RegisterDayWeekWork();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterDayWeekWorkActionPerformed

    private void BusesRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusesRegisterActionPerformed
        int numberBuses = Integer.parseInt(JOptionPane.showInputDialog(" total buses to be registered "));
        MenuOption.arreglo.createArregloWeek(numberBuses);
        this.dispose();
        RegisterBuses window = new RegisterBuses();
        window.setVisible(true);  
    }//GEN-LAST:event_BusesRegisterActionPerformed

    private void AnalysisWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisWeekActionPerformed
        AnalysisWeek window = new AnalysisWeek();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnalysisWeekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuOption().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalysisWeek;
    private javax.swing.JButton BusesRegister;
    public javax.swing.JButton RegisterDayWeekWork;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
