/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.ListaDoblementeEnlazadasCircular;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author juan
 */
public class Main extends javax.swing.JFrame {
    
    public static ListDoublyLinked names = new ListDoublyLinked();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    
    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddFirtsNodo = new javax.swing.JButton();
        AddEndNodo = new javax.swing.JButton();
        AddAfterNodo = new javax.swing.JButton();
        InsertVolumenNodo = new javax.swing.JButton();
        AddBeforeNodo = new javax.swing.JButton();
        InsertVolumenLinked = new javax.swing.JButton();
        AddFirtsLinked = new javax.swing.JButton();
        AddEndLinked = new javax.swing.JButton();
        AddIndexLinked = new javax.swing.JButton();
        InformationLinked = new javax.swing.JButton();
        InformationNodo = new javax.swing.JButton();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("LinkedList ");

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel2.setText("Nodos enlasados ");

        AddFirtsNodo.setText("Add Firts");
        AddFirtsNodo.addActionListener(this::AddFirtsNodoActionPerformed);

        AddEndNodo.setText("Add  end ");
        AddEndNodo.addActionListener(this::AddEndNodoActionPerformed);

        AddAfterNodo.setText("Add after");
        AddAfterNodo.addActionListener(this::AddAfterNodoActionPerformed);

        InsertVolumenNodo.setText("Insert Volumen");
        InsertVolumenNodo.addActionListener(this::InsertVolumenNodoActionPerformed);

        AddBeforeNodo.setText("Add Before");
        AddBeforeNodo.addActionListener(this::AddBeforeNodoActionPerformed);

        InsertVolumenLinked.setText("Insert Volumen");

        AddFirtsLinked.setText("Add Firts");

        AddEndLinked.setText("Add end");
        AddEndLinked.addActionListener(this::AddEndLinkedActionPerformed);

        AddIndexLinked.setText("Add Index");

        InformationLinked.setText("Information");

        InformationNodo.setText("Information");
        InformationNodo.addActionListener(this::InformationNodoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddIndexLinked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsertVolumenLinked, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(AddFirtsLinked, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEndLinked, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InformationLinked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(304, 304, 304)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InsertVolumenNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddFirtsNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEndNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddAfterNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddBeforeNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InformationNodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertVolumenNodo)
                    .addComponent(InsertVolumenLinked))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFirtsNodo)
                    .addComponent(AddFirtsLinked))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEndNodo)
                    .addComponent(AddEndLinked))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddIndexLinked)
                    .addComponent(AddAfterNodo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBeforeNodo)
                    .addComponent(InformationLinked))
                .addGap(18, 18, 18)
                .addComponent(InformationNodo)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFirtsNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFirtsNodoActionPerformed
        String name = JOptionPane.showInputDialog(" Enter the name ");
        names.addFirts(name);
    }//GEN-LAST:event_AddFirtsNodoActionPerformed

    private void AddEndNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEndNodoActionPerformed
        String name = JOptionPane.showInputDialog(" Enter the name ");
        names.addlast(name);
    }//GEN-LAST:event_AddEndNodoActionPerformed

    private void AddEndLinkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEndLinkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEndLinkedActionPerformed

    private void InsertVolumenNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertVolumenNodoActionPerformed
        
        String name = "user";
        String[] names = new String[1000000];
        for(int x = 0; x < 1000000; x++){
            names[x] = name+" "+x;
        }
        long tiempoInicio = System.nanoTime();
        Main.names.addBig(names);
        long tiempoFinal = System.nanoTime();
        double duracion = (tiempoFinal-tiempoInicio)/1_000_000_000.0;
        
        JOptionPane.showMessageDialog(null,duracion);
    }//GEN-LAST:event_InsertVolumenNodoActionPerformed

    private void AddAfterNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAfterNodoActionPerformed
        int index = Integer.parseInt(JOptionPane.showInputDialog(" Enter the index "));
        String name = JOptionPane.showInputDialog(" Enter the name ");
        names.addAfter(index, name);
    }//GEN-LAST:event_AddAfterNodoActionPerformed

    private void AddBeforeNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBeforeNodoActionPerformed
        int index = Integer.parseInt(JOptionPane.showInputDialog(" Enter the index "));
        String name = JOptionPane.showInputDialog(" Enter the name ");
        names.addBefore(index, name);
    }//GEN-LAST:event_AddBeforeNodoActionPerformed

    private void InformationNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationNodoActionPerformed
        
        
        InformationView view = new InformationView();
        view.setVisible(true);
    }//GEN-LAST:event_InformationNodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAfterNodo;
    private javax.swing.JButton AddBeforeNodo;
    private javax.swing.JButton AddEndLinked;
    private javax.swing.JButton AddEndNodo;
    private javax.swing.JButton AddFirtsLinked;
    private javax.swing.JButton AddFirtsNodo;
    private javax.swing.JButton AddIndexLinked;
    private javax.swing.JButton InformationLinked;
    private javax.swing.JButton InformationNodo;
    private javax.swing.JButton InsertVolumenLinked;
    private javax.swing.JButton InsertVolumenNodo;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
