/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arreglos;

import javax.swing.JOptionPane;

/**
 *
 * @author juan
 */
public class MenuOption extends javax.swing.JFrame {
    
    Arreglos objArray = new Arreglos();
    Matriz objMatriz = new Matriz();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuOption.class.getName());

    /**
     * Creates new form MenuOption
     */
    public MenuOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Create = new javax.swing.JButton();
        t = new javax.swing.JTextField();
        View = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        CreateMatriz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ConsultarMatriz = new javax.swing.JButton();
        EliminarPosicionMatriz = new javax.swing.JButton();
        ActualizarMatriz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Create.setText("Create");
        Create.setEnabled(false);
        Create.addActionListener(this::CreateActionPerformed);

        t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tKeyReleased(evt);
            }
        });

        View.setText("View");
        View.setEnabled(false);
        View.addActionListener(this::ViewActionPerformed);
        View.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ViewKeyReleased(evt);
            }
        });

        Update.setText("Update");
        Update.setEnabled(false);
        Update.addActionListener(this::UpdateActionPerformed);

        Delete.setText("Delete");
        Delete.setEnabled(false);
        Delete.addActionListener(this::DeleteActionPerformed);

        CreateMatriz.setText("CreateMatriz");
        CreateMatriz.addActionListener(this::CreateMatrizActionPerformed);

        jLabel1.setText("Tamaño Arreglo");

        ConsultarMatriz.setText("ConsultarMatriz");
        ConsultarMatriz.setEnabled(false);
        ConsultarMatriz.addActionListener(this::ConsultarMatrizActionPerformed);

        EliminarPosicionMatriz.setText("EliminarPosicionMatriz");
        EliminarPosicionMatriz.setEnabled(false);
        EliminarPosicionMatriz.addActionListener(this::EliminarPosicionMatrizActionPerformed);

        ActualizarMatriz.setText("ActualizarMatriz");
        ActualizarMatriz.setEnabled(false);
        ActualizarMatriz.addActionListener(this::ActualizarMatrizActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Delete)
                    .addComponent(Update)
                    .addComponent(View)
                    .addComponent(Create))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarPosicionMatriz)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ActualizarMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(ConsultarMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreateMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Create)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(View)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EliminarPosicionMatriz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarMatriz)
                    .addComponent(Update))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarMatriz)
                    .addComponent(Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateMatriz)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        
        objArray.createArray(Integer.parseInt(t.getText()));
        if(objArray.names != null){
            View.setEnabled(true);
            Update.setEnabled(true);
            Delete.setEnabled(true);
        }
    }//GEN-LAST:event_CreateActionPerformed

    private void tKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKeyReleased

        if(t.getText().equals("")){
            JOptionPane.showMessageDialog(null, " !Error Up¡ rellena el campo");
            Create.setEnabled(false);
        }else{
            Create.setEnabled(true);
            try{
                int n = Integer.parseInt(t.getText());
            }catch(NumberFormatException e){
                Create.setEnabled(false);
                JOptionPane.showMessageDialog(null, " campo rellenado incorrectamente");
            }
        }
    }//GEN-LAST:event_tKeyReleased

    
    private void ViewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ViewKeyReleased
         
    }//GEN-LAST:event_ViewKeyReleased

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        objArray.viewArray();
    }//GEN-LAST:event_ViewActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        
        String index = JOptionPane.showInputDialog(" index ");
        String name = JOptionPane.showInputDialog(" name ");
       
        if(objArray.verifyIndex(index)){
            objArray.updateArray(Integer.parseInt(index), name);
        }
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       
        String index = JOptionPane.showInputDialog(" index ");
        
        if(objArray.verifyIndex(index)){
            objArray.deleteArray(Integer.parseInt(index));
        }
        
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void CreateMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMatrizActionPerformed
        
        String fila = JOptionPane.showInputDialog(" ingrese el numero fila ");
        String col = JOptionPane.showInputDialog(" ingrese el numero columna");
        objMatriz.crearMatriz(fila,col);
        if(objMatriz.datos != null){
            ActualizarMatriz.setEnabled(true);
            ConsultarMatriz.setEnabled(true);
            EliminarPosicionMatriz.setEnabled(true);
        }
    }//GEN-LAST:event_CreateMatrizActionPerformed

    private void ActualizarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarMatrizActionPerformed
        objMatriz.actualizarMatriz(JOptionPane.showInputDialog(" ingrese valor fila"),JOptionPane.showInputDialog(" ingrese valor columna"),JOptionPane.showInputDialog(" ingrese valor a cambiar"));
    }//GEN-LAST:event_ActualizarMatrizActionPerformed

    private void ConsultarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarMatrizActionPerformed
        
        objMatriz.consultarMatriz(JOptionPane.showInputDialog(" ingrese el valor a consultar "));
    }//GEN-LAST:event_ConsultarMatrizActionPerformed

    private void EliminarPosicionMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPosicionMatrizActionPerformed
        objMatriz.eliminarPosicion(JOptionPane.showInputDialog(" ingrese la fila "),JOptionPane.showInputDialog(" ingrese la columna "));
    }//GEN-LAST:event_EliminarPosicionMatrizActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuOption().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarMatriz;
    private javax.swing.JButton ConsultarMatriz;
    private javax.swing.JButton Create;
    private javax.swing.JButton CreateMatriz;
    private javax.swing.JButton Delete;
    private javax.swing.JButton EliminarPosicionMatriz;
    private javax.swing.JButton Update;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
